### ISSUE TITLE
Limit on the number of handles exceeded

### ISSUE THREAD

**Issue by Fredehagelund92** [blue-yonder/turbodbc#114]
Not sure wether this is odbc driver related from the vendor, however when i try to iterate through big csv file and insert each row into EXASOL i get following error: `Limit on the number of handles exceeded`. How come i get this error. The csv file is 10 mb

```
for line in reader:
    # Insert row
    exasol.do_INSERT("INSERT INTO {0}.{1} ({2}) VALUES ({3})".format(project.staging_table_name,target_table, ','.join(header), ','.join(line)))

#Commit
exasol.commit_QUERY()

```

**Comment by MathMagique** [comment]
Hi there! From the code snippet you provided, I am afraid that I am not even sure if you are using turbodbc ;-). I have no idea what the `exasol` instance is supposed to be, and neither `do_INSERT` nor `commit_QUERY` are methods provided by turbodbc.

Assuming above snippet uses turbodbc one way or the other, you are essentially creating a new statement for each line you insert. This is not very efficient and might lead to the error message you experience, though I assume that this is a limitation of the Exasol ODBC driver.

With plain turbodbc, you could probably avoid the error message and be more efficient with this snippet:

```
query = "INSERT INTO {1}.{2} ({3}) VALUES ({4})".format(project.staging_table_name,
                                                        target_table,
                                                        ','.join(header),
                                                        ','.join(['?' for _ in header]))

connection = turbodbc.connect(dsn="My Exasol connection")
cursor = connection.cursor()
cursor.executemany(query, reader)
connection.commit()
```

This builds the query _once_, and transfers parameters in bulk via `executemany` in a single statement. Since `reader` is an iterable over parameter sets, it is directly usable in `executemany`.

**Comment by Fredehagelund92** [comment]
Sorry for the confusion, i've created a wrapper for turbodbc, so thats why `.exasol`. but worked like a charm

**Comment by MathMagique** [comment]
Glad to have helped.
