### ISSUE TITLE
Cursors not closed when leaving function scope

### ISSUE THREAD

**Issue by thpfaff** [blue-yonder/turbodbc#146]
[reproduce.py.txt](https://github.com/blue-yonder/turbodbc/files/1682402/reproduce.py.txt)

When running this example under Debian 7 the program gets killed after 50 something iterations.

**Comment by MathMagique** [comment]
Hi Thomas! Thanks for reporting, I'll need to have a look. That may have something to do with connections keeping cursors alive in an inadequate way.

**Comment by MathMagique** [comment]
On my OSX machine, I get to about 400 iterations until I get the error:
```
turbodbc.exceptions.DatabaseError: ODBC error
state: HY014
native error code: -1
message: [EXASOL][EXASolution driver]Limit on the number of handles exceeded.
```

**Comment by MathMagique** [comment]
The issue is fixes. The connection object had a record of cursors so they can could closed when the connection is closed. This record unintentionally prohibited the garbage collection of cursors, so the user had to manually close cursors to avoid the reported error message.

The fixed record is made up of weak references so that garbage collection works as expected.
