### ISSUE TITLE
Memory issues with readarrowbatches

### ISSUE THREAD

**Issue by mariusvniekerk** [blue-yonder/turbodbc#175]
When iterating through a large resultset with `fetch_arrow_batches` it appears as if memory usage increases monotonically.

`pa.total_allocated_bytes()` seems to remain pretty stable.

Are there any other things to go look at for diagnosis?

Total memory consumption
![image](https://user-images.githubusercontent.com/73973/42895029-9882c858-8a86-11e8-98a3-dd6906c2c002.png)
Arrow allocated bytes
![image](https://user-images.githubusercontent.com/73973/42895037-a0f5c7d8-8a86-11e8-82b4-762b5da6c6de.png)

This process loops over a list of tables

**Comment by MathMagique** [comment]
Yeah, those ODBC drivers sometimes try to do clever things (caching) so the application can use the ODBC API in a less than clever way. Sometimes, one has to tell the driver to not do clever things in order to work with more clever applications (turbodbc). For example, MySQL's ODBC driver tries to cache the entire result set by default, if I am not mistaken.

Anyway, I'm glad you have solved your issue!
