### ISSUE TITLE
Turbodbc fetching half/partial result sets

### ISSUE THREAD

**Issue by sivaaug3** [blue-yonder/turbodbc#211]
I am using turbodbc to connect to Sybase ASE. When using fetchall()  only partial result sets are fetched, for example If i try to fetch 4 records first two records will have values, next two are two empty lists. Same query works well with pyodbc.

**Comment by sivaaug3** [comment]
Adding to above, if I fetch 100 records , first 50 will have rows/values and other 50 has empty lists. Is there anything to do with cursor skip/count ?

**Comment by MathMagique** [comment]
Just a few thoughts:
* Do you have `use_async` enabled? Try disabling it.
* Sometimes drivers were built with certain 32-bit fields in mind rather than the 64 bits that turbodbc assumes. Can you try a different ODBC driver?
* Which platform are you using?
* Can you check the contents of these 50 rows to determine whether you get the first 50 rows or every other row (1, 3, 5, 7, etc.)?
* One key difference between turbodbc and pyodbc is that turbodbc uses `SQLFetchScroll` to retrieve batches (although there is no scrolling in the sense of going forward and backward). If the driver is not correctly implementing this, there may be issues.

**Comment by sivaaug3** [comment]
Hi, my issue is resolved. I was using 32 bit odbc drivers in Redhat Linux. After changing to 64 bit i am able to process the rows correctly.

**Comment by MathMagique** [comment]
Glad to hear your issue is resolved!
