### ISSUE TITLE
can support jdbc?

### ISSUE THREAD

**Issue by wonb168** [blue-yonder/turbodbc#362]
turbodbc is so good, but need odbc, can directly use jdbc? it's not easier to install odbc in linux .
and pip install turbodbc raise error in my win10 :
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

but  I install C++14.5, and rebooted my pc.

**Comment by pacman82** [comment]
Long time since I contributed to turbodbc, but I feel there is no chance `turbodbc` is ever going support to JDBC as its sole purpose is to provide Python bindings to ODBC, and implement buffers for bulk queries. Well that's two purposes, but binding to JDBC isn't one of them.

You see, interfacing with ODBC is very natural for a C++ backend as ODBC exposes a C-Interface. Interfacing with the JVM for JDBC is whole other ballpark. Using a different set of tools (and even programming languages) to achieve something else (interfacing with JDBC instead of ODBC) arguably puts this out of scope of turbodbc.

Arguably only because the supported usecases are very similar.

What are you trying to use ODBC for?

FYI: pip installing it might not get you very far, unless you have all the build dependencies available, but a conda environment might enable you to install the package.

Cheers
