### ISSUE TITLE
Request to replace boost Gregorian with Standard C++ component

### ISSUE THREAD

**Issue by yalwan-scee** [blue-yonder/turbodbc#54]
Currently, due to the use of `boost::gregorian::date`, dates which come from the RDBMS with years outside the range
1400 to 10000
will fail to convert

Replacing `boost::gregorian::date` with standard C++ library components should allow dates outside of this range, and move part of the way to reducing turbodbc dependency on boost.

**Comment by yalwan-scee** [comment]
Is std::tm appropriate for this?

**Comment by xhochy** [comment]
@yalwan-scee Have a look at the code in my `turbodbc_arrow` PR: https://github.com/blue-yonder/turbodbc/pull/26/files#diff-1d245e065fddf7d92ba50c77af7b3d20R72 It already does quite the same without boost.

**Comment by yaxxie** [comment]
I noticed this is giving milliseconds since epoch even though the functions is named `date_to_days`
In particular I am not sure of the correct way to compute the number of days between two dates using std::tm to represent dates. Any insights on this?

**Comment by xhochy** [comment]
@yaxxie yes, that's due to the special definition of Apache Arrow's DATE type which is "milliseconds since the epoch but only interpret the date part". To get the days since epoch, you need to simply divide by `86400000`.

**Comment by yaxxie** [comment]
I got a little stuck after I replaced all instances of boost::gregorian::date with std::tm where the tests fail to compile because there is not an operator<< defined for std::tm....

I am not sure what approach you guys would take to handle this? The dumb thing to do is to implement it using asctime but I have no idea where the implementation should live. My first thought would be in the test because only the tests do this, but I really have no idea what your preferences would be on this.

> [ 60%] Building CXX object cpp/turbodbc/Test/CMakeFiles/turbodbc_test.dir/tests/description_test.cpp.o
> In file included from /usr/include/boost/variant/variant.hpp:2415:0,
>                  from /home/yaxattax/git/turbodbc/cpp/turbodbc/Library/turbodbc/field.h:3,
>                  from /home/yaxattax/git/turbodbc/cpp/turbodbc/Library/turbodbc/description.h:3,
>                  from /home/yaxattax/git/turbodbc/cpp/turbodbc/Test/tests/description_test.cpp:1:
> /usr/include/boost/variant/detail/variant_io.hpp: In instantiation of ‘void boost::detail::variant::printer<OStream>::operator()(const T&) const [with T = tm; OStream = std::basic_ostream<char>]’:
> ...
> /home/yaxattax/git/turbodbc/cpp/turbodbc/Test/tests/description_test.cpp:103:1:   required from here
> /usr/include/boost/variant/detail/variant_io.hpp:64:14: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const tm’)
>          out_ << operand;

**Comment by MathMagique** [comment]
Hm. I guess there is two parts in here. One part is getting rid of `boost::gregorian::date` when doing the conversion for Python. The other thing is that the same type is also used for C++ end users (that do not really exist, I might add).

So I would replace the gregorian thing only in the turbodbc_python porject folder. I will make a move to extract all things only relevant to C++ users to a separate library that will not be included in the Python source distribution.

**Comment by yaxxie** [comment]
I didn't find any references to this type within turbodbc_python, as you can see from the commits in PR62, turbodbc and turbodbc_numpy had references, I replaced them all. I think it was necessary to replace in the C++ anyway, because they python objects come through from the C++ library, and boost was already throwing the exception there.

**Comment by MathMagique** [comment]
Of course, you are completely right, there are no references to `boost::gregorian` in `turbodbc_python`. I meant the occurrences at `turbodbc_numpy` that you mentioned.

The Python objects do not come from the C++ library; at least not from that part. Here's what happens when selecting data:

* An instance of `bound_result_set` [is created](https://github.com/blue-yonder/turbodbc/blob/master/cpp/turbodbc/Library/src/command.cpp#L28) when the query has a result set.
* A column type [is selected](https://github.com/blue-yonder/turbodbc/blob/master/cpp/turbodbc/Library/src/make_description.cpp#L85) based on what [the database returns](https://github.com/blue-yonder/turbodbc/blob/master/cpp/turbodbc/Library/src/result_sets/bound_result_set.cpp#L39)
* Columns only know about the C types provided by the ODBC library.
* The Python result set [takes a reference to a base `result_set`](https://github.com/blue-yonder/turbodbc/blob/master/cpp/turbodbc_python/Library/turbodbc_python/python_result_set.h#L20).
* The `field_result_set` that uses the variant stuff [is not a child class of `result_set`](https://github.com/blue-yonder/turbodbc/blob/master/cpp/turbodbc/Library/turbodbc/result_sets/field_result_set.h#L14)

A few months ago you would have been right, because at that time all values from the database were converted to "proper" C++ types (the ones listen in `field`), and then `field` was converted to Python. This intermediate step introduced quite some overhead, so I removed it. I should have (re)moved the now superfluous C++ code bits at the same time to avoid confusion. I am sorry that this has lead to extra work for you.

**Comment by yalwan-scee** [comment]
Can we reasonably act on this? We discovered dates drift if we use the naive computations; in my mind it looks like that it is not trivial to replace this component in the code. Close as wontfix?

**Comment by MathMagique** [comment]
As much as I want it to be different, I think you are right. Perhaps another time, but there is no point in having this issue rot.
