### ISSUE TITLE
Can't build master on macOS Sierra

### ISSUE THREAD

**Issue by dirkjonker** [blue-yonder/turbodbc#63]
I can't build the latest master on macOS Sierra anymore using Python 3.5 or 3.6.

During `make`:

```
[ 10%] Building CXX object cpp/cpp_odbc/Library/CMakeFiles/cpp_odbc.dir/src/level2/level1_connector.cpp.o
/Users/Dirkjonker/src/turbodbc/cpp/cpp_odbc/Library/src/level2/level1_connector.cpp:361:43: error: no matching member function for call to 'prepare_statement'
    auto const return_code = level1_api_->prepare_statement(handle.handle, buffered.data_pointer(), buffered.size());
                             ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/Users/Dirkjonker/src/turbodbc/cpp/cpp_odbc/Library/cpp_odbc/level1/api.h:117:15: note: candidate function not viable: no known conversion from 'unsigned short *' to 'SQLCHAR *'
      (aka 'unsigned char *') for 2nd argument
    SQLRETURN prepare_statement(SQLHSTMT statement_handle, SQLCHAR * statement_text, SQLINTEGER text_length) const;
              ^
/Users/Dirkjonker/src/turbodbc/cpp/cpp_odbc/Library/cpp_odbc/level1/api.h:122:15: note: candidate function not viable: no known conversion from 'unsigned short *' to 'SQLWCHAR *'
      (aka 'wchar_t *') for 2nd argument
    SQLRETURN prepare_statement(SQLHSTMT statement_handle, SQLWCHAR * statement_text, SQLINTEGER text_length) const;
              ^
1 error generated.
make[2]: *** [cpp/cpp_odbc/Library/CMakeFiles/cpp_odbc.dir/src/level2/level1_connector.cpp.o] Error 1
make[1]: *** [cpp/cpp_odbc/Library/CMakeFiles/cpp_odbc.dir/all] Error 2
make: *** [all] Error 2
```

1.0.5 builds without any errors. Also, on Centos 7, no problems.

**Comment by MathMagique** [comment]
That's weird; travis CI does not complain about it and I can compile things on my MacBook as well.

I think the issue may be that you are using `iodbc` to build turbodbc. [This issue](https://bugs.documentfoundation.org/show_bug.cgi?id=83924) provides some background information. `iodbc` uses a 32 bit wchar_t type for wide SQL strings, while `unixodbc` and Microsoft's original ODBC use 16 bit types (such as `unsigned short`).

I'd recommend to install `unixodbc`, since that's the thing turbodbc is tested with. `iodbc` is no longer shipped with recent versions of OSX.

You don't see the issue with 1.0.5 because 1.0.5 did not use wide strings at all. You don't see the issue on Centos because it uses `unixodbc`.

**Comment by dirkjonker** [comment]
You are exactly right, I looked at the cmake output and it shows:
```
-- Detecting unixODBC library
--   Found header files at: /Library/Frameworks/iODBC.framework/Headers
--   Found library at: /usr/local/lib/libodbc.dylib
```
Funny thing is, I do have unixODBC installed, but Homebrew probably did not link it or something.

**Comment by dirkjonker** [comment]
Nope, link from homebrew were just fine, `/usr/local/lib/libodbc.dylib` points to unixODBC, however the unixODBC headers are at `/usr/local/include`

**Comment by MathMagique** [comment]
So the headers used for compiling are different from the library that is linked? That sounds a little problematic to me ;-).

**Comment by dirkjonker** [comment]
Got rid of iODBC, now it works fine
```
-- Detecting unixODBC library
--   Found header files at: /usr/local/include
--   Found library at: /usr/local/lib/libodbc.dylib
```

**Comment by MathMagique** [comment]
You can try setting the `UNIXODBC_INCLUDE_DIR` environment variable before calling the `cmake` command.

**Comment by MathMagique** [comment]
Glad you got it running!
