### ISSUE TITLE
issue with cyrillic field names and pandas

### ISSUE THREAD

**Issue by nvm1** [blue-yonder/turbodbc#92]
Hi there,

I have a piece of code that is used to load sql query results into pandas dataframe:

    import turbodbc
    import pandas as pd
    
    connect = turbodbc.connect(dsn='mydsn')
    df = pd.read_sql('select * from table1',connect)

The problem is that if in the table (or view like in my case) there are cyrillic symbols **in the field names**, when I try to load results into the df I get error 

> 'utf-8' codec can't decode byte 0xce in position 0: invalid
> continuation byte.

This error appears both with prefer_unicode=True and without.

Recent version of pyodbc (4.0.16) works alright, but pyodbc 3.0.7 (the one that is included into anacoda by default) has the same issue.

Is it possible to fix it without changing the field names?

**Comment by MathMagique** [comment]
@nvm1 Which database are you trying to access?

**Comment by nvm1** [comment]
Well, I've just completed test on mysql. It doesn't throw errors, but shows ???? instead of field names (unicode driver).

I recieve decode error on Tibero database, which is quite rare and I'm not sure you can repeat the test. I'm not able to test it on any other database unfortunately.

Here is how you can test on mysql (5.7 in my case):
```
create table test (
	`поле1` varchar(100)
);
insert into test values('1');
```

```
import turbodbc
import pandas as pd

connect = turbodbc.connect(dsn='mysq_unicode_odbc_driverl')

df = pd.read_sql('select * from omt.test',connect)

```

**Comment by MathMagique** [comment]
Thanks for the quick update! The `prefer_unicode` thing is a rather new addition, and currently it only spans parameters, result sets, and the query text itself. That means that indeed `prefer_unicode` will not solve your problem. While this issue is not fully resolved, you could try the following things:

* If you have a choice of ANSI and Unicode drivers, try the ANSI driver. For ANSI drivers, try to set the session encoding (or similar option) to UTF-8. If there is no session locale option, you can try setting the `LOCALE` environment variable to an UTF-8 locale.
* Use a different query that maps the column names in your view to ASCII names.
* Try to retrieve data via another view that maps the cyrillic column names of your original view to ASCII names.
* Use a different query (`SELECT cyrillic_name AS ascii_name, ...`) that maps the column names in your view to ASCII names.

Try to combine options 2 and 3 with `prefer_unicode`.

On another note, I would suggest not to use `pd.read_sql()`, because the [documentation](http://pandas.pydata.org/pandas-docs/version/0.20/generated/pandas.read_sql.html) claims that this only supports SQLite if you do not use SQLAlchemy at the same time. The preferred and likely _way_ faster method should be this:
```
import turbodbc
import pandas as pd

connection = turbodbc.connect(dsn='my DSN')
cursor = connection.cursor()
cursor.execute('SELECT * FROM table')
df = pd.Dataframe(data=cursor.fetchallnumpy())
```

Final note: Tibero - never heard of that one :-)

**Comment by nvm1** [comment]
Thank you a lot for the quick response!

The problem with mapping cyrillic column names is that I can't actually change the names. We have a reporting system that loads data into excel spreadsheet and that excel spreadsheet is the source for powerpoint presentation (this way it's possible to update charts in the presentation automatically). If I change the names, they will be changed in the presentation which doesn't suit stakeholders(doh..).

I tried your suggestion with ansi driver on mysql and it worked like a charm. Unfortunatelly most of the data we have is in Tibero. I'll try to fight it with locale settings, but I couldn't fix it last time with pyodbc untill I installed the updated version.

You didn't miss much if you've never heard about Tibero. It's like Oracle, but korean ;)

I'll update the topic if I find any solution to this.

**Comment by MathMagique** [comment]
Well, you _could_ rename the things in the _query_ to `cursor.fetchallnumpy()`. This will generate an `OrderedDict` with ASCII column names as keys. Then you could just rename the keys of this dictionary back to the original cyrillic names, and pass the dictionary with the cyrillic names to `Dataframe(data=cyrillic_dict)`. The resulting dataframe would then look just as you are used to, and stakeholders will be happy :-).

I know it is ugly, but there is a chance that it actually works and gives you a performance edge.

**Comment by nvm1** [comment]
Thank you, I'll see to it.
One thing I want to ask, if you may look at cursor.py file and description function (lines 57-60). I see that when I make query with cyrillic names it fails on line 59 or 60. Maybe it can be easily solved with trying to decode utf8 somewhere there, but I can't actually understand much of what's going on in there due to lack of experience.

**Comment by MathMagique** [comment]
There's not too much to see at this function, I fear. The problem is at the C/C++ level and not fixable in Python alone. A C function is used to get strings of 8-byte characters. Since the ODBC API does not really enforce how these strings are encoded (UTF-8, Latin-1, Cyricllic, etc), turbodbc _assumes_ that most sane databases would use UTF-8. When converting this to a real Unicode string for Python, errors happen when the string is _not_ encoded with UTF-8. That is the case here. The fix is to use another function of the ODBC API that has a _somewhat_ defined encoding.

**Comment by nvm1** [comment]
Hi there,
I didn't find any suitable solution for now beside switching engine to pyodbc in case I recieve utf-8 decoding error. That's a shame, but since I do not have to select cyrillic fields quite often it suits me well.

In other cases I see that turbodbc works like a charm and is much faster than other odbc solutions for python. Thank you!

**Comment by MathMagique** [comment]
Sorry to hear about the unsatisfying solution. I'll keep this issue open until I have implemented better treatment of unicode column names.

**Comment by nvm1** [comment]
Hi there,

I've just tested the 2.0.0 version with cyrillic field names. It works like a charm! Thank you very much, you've made my day!

**Comment by MathMagique** [comment]
You have just made mine as well :-).
