### ISSUE TITLE
No active result set

### ISSUE THREAD

**Issue by Fredehagelund92** [blue-yonder/turbodbc#98]
I've added a create table to the `cursor.execute`however i keep getting following exception even though the table is created. is there anyway to ignore this error:

```
_assert_valid_result_set
    raise InterfaceError("No active result set")
turbodbc.exceptions.InterfaceError: No active result set
```

**Comment by MathMagique** [comment]
Hi! Since you have closed the issue, were you able to resolve it yourself?

**Comment by Fredehagelund92** [comment]
Yes! sorry it was my loop that was wrong i was doing `for table in cursor`, however `for table in cursor.fetchall()` silenced the error.

**Comment by MathMagique** [comment]
I'm still not sure what happened there, since iterating over the cursor should be equivalent to iterating over `fetchall()`, since `fetchall()` is implemented like this:

```
def fetchall(self):
    return [row for row in self]
```

My best bet right now is that the `execute()` call you made before did not yield a result set. At least, that is what the error message hints at. But in this case, the `fetchall()` should not make a difference.

**Comment by Fredehagelund92** [comment]
I'm not sure if i can reproduce, but i had something like below code, where i loop through `SOURCE_SCHEMA` in order to get schemas to be fetched and then i execute a EXASOL script that generates the tables statements, from the source and in the next loop i run these statements. however i kept getting the `No active result set` error. i then commented the `for table in tables:` loop and the i got `index out of bounds` on `connection[2]` even though it worked fine when i tried `print(connection[2])`. in the end i then added `fetchall()` as mentioned and everything worked. hope that provide a little more information

```
connections = cursor.execute("SELECT * METADATA.SOURCE_SCHEMA;")

for connection in connections:

  tables = cursor.execute("EXECUTE SCRIPT STAGING.LOAD_FROM_MYSQL('" + connection[1] + "', '" + connection[2] + "');")

  for table in tables:

      cursor.execute(table[0])
```

**Comment by MathMagique** [comment]
Ok, that somewhat explains things ;-). You have _two_ loops, and both loop over a result set from the database. The thing is, when you call `execute()`, any old result sets are discarded. Once you finish the tables loop inside the connections loop, the result set will be finished. When you try to continue with the next iteration in the connections loop, the first result set is gone, too. Hence the error message you see. A `fetchall()` in the connections loop would indeed fix that.

Side remark: Since `execute()` returns the `Cursor` object, it is probably misleading to assign the Cursor object to two other variables.
